# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160905_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
