# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160906_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
