# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(),
        ),
    ]
