# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20160914_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(max_length=500),
        ),
    ]
