# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20160914_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_id',
            new_name='tmdb_id',
        ),
    ]
