# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20160915_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
