# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20160915_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
