# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20160916_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
