# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20160929_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
