# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20161001_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_score',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.ManyToManyField(null=True, to='movies.Trailer'),
        ),
    ]
