# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20161001_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
