# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20161002_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_score',
        ),
    ]
