# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_remove_movie_imdb_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='writer',
        ),
    ]
